#######################################################################################
# Book settings
title : Investing Reference Book
author: David Li
logo: 'investing.png'

# Information about where the book exists on the web
description: >-
  A complication of my efforts to learn the stock market and obtain financial independence.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : auto
  exclude_patterns:
    - 'analyze/**'
    - 'mini_book/notebooks/references/stock_predictions.ipynb'

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/dli-invest/iref-book
  path_to_book                : "ibook"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex